# Generated by Django 4.2.30 on 2026-08-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_update_about_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='brand_subbrand_text',
            field=models.CharField(blank=True, default='London', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_company_about_label',
            field=models.CharField(blank=True, default='About LIAFE', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_company_contact_label',
            field=models.CharField(blank=True, default='Contact Us', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_company_heading',
            field=models.CharField(blank=True, default='Company', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_company_home_label',
            field=models.CharField(blank=True, default='Home', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_contact_heading',
            field=models.CharField(blank=True, default='Contact', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_domain_text',
            field=models.CharField(blank=True, default='www.ukliafe.com', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_services_heading',
            field=models.CharField(blank=True, default='Services', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='nav_consult_button_text',
            field=models.CharField(blank=True, default='Consult Us', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='nav_contact_label',
            field=models.CharField(blank=True, default='Contact', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='nav_home_label',
            field=models.CharField(blank=True, default='Home', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='nav_services_label',
            field=models.CharField(blank=True, default='Services', max_length=50),
        ),
    ]
