# Generated by Django 4.2.30 on 2026-08-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesetting_nav_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'AAOIFI Aligned'", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trust Badge',
                'verbose_name_plural': 'Trust Badges',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='section_name',
            field=models.CharField(choices=[('hero', 'Hero'), ('about', 'About'), ('core_services', 'Core Services'), ('why_choose_us', 'Why Choose Us'), ('approach', 'Approach'), ('cta', 'CTA'), ('trust_strip', 'Trust Strip')], max_length=64, unique=True),
        ),
    ]
