# Generated by Django 4.2.30 on 2026-08-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seed_trust_badges'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(editable=False, help_text='Internal identifier, fixed at creation. Not shown in the dashboard.', max_length=120, unique=True)),
                ('group', models.CharField(choices=[('global', 'Global / Shared'), ('home', 'Homepage'), ('academy', 'Academy Page'), ('research', 'Research House Page'), ('shariah', 'Shariah Advisory Page'), ('publication', 'Publication Page'), ('contact', 'Contact Page')], default='global', max_length=20)),
                ('label', models.CharField(help_text='Shown in the dashboard so you know what this controls', max_length=200)),
                ('value', models.TextField(blank=True, help_text="Leave blank to use the site's default text")),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Text',
                'verbose_name_plural': 'Page Text',
                'ordering': ['group', 'order', 'label'],
            },
        ),
    ]
