# Generated by Django 4.2.30 on 2026-08-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='nav_subtitle',
            field=models.CharField(blank=True, help_text='Short line shown in the header dropdown / footer. Leave blank to reuse the short description.', max_length=150),
        ),
    ]
